### ISSUE TITLE
Cryptography implementations.

### ISSUE THREAD

**Issue by Abhiramborige** [Abhiramborige/Crypto-systems#1]
Implementations in any language is ok. Must be helpful for the beginners in cryptographical implementations through programming and realize that programming is just fun and makes life easier, !!!✌😃😎

**Comment by Qubit-Hex** [comment]
hey i have a Caesar cipher, but with adjustable prams for beginners on  my page its written in js and very well commented.

**Comment by Abhiramborige** [comment]
Hey, the implementation is awesome. And Boomboom was 🔥. 
But I didnt understand the usage of Mapkeys, Mapshift, and Unpack. 
If u want to contribute, you can proceed!!

**Comment by Qubit-Hex** [comment]
> Hey, the implementation is awesome. And Boomboom was 🔥.
> But I didnt understand the usage of Mapkeys, Mapshift, and Unpack.
> If u want to contribute, you can proceed!!

ok, i will adjust the code a little to make it more understandable.
map keys create a dictionary object ex: [a] = [a] for whole dictionary a-z 0-9
map shift  take the value returned from mapkeys the dictionary and applys the shift ex 2 
will return [a] = c
unpack will decrypt the message using shift provided in a parms
boomboom is a function that uses unpack and pretty much loops it to a limit
i also have all the tests commented to using console.log you will see what each one does.

**Comment by Qubit-Hex** [comment]
well i updated some of the code im new to github so how do i contribute was
trying for hour but didn't see the new file.

also on side note im working on a project atm, if you have any background
on business and accounting it would help me out alot.

**Comment by Abhiramborige** [comment]
Hi, Thanks for the contribution, I also have checked how tests work. It was good.
You have the right way to create a PR, so the hour you spent wasn't in vain !!.
I am student right now and don't have any business background atm. If u have anything like that, it would help me al lot.
Thanks 👍 :)

**Comment by Abhiramborige** [comment]
Done, putting again for hacktoberfest :)

**Comment by Qubit-Hex** [comment]
?

**Comment by Abhiramborige** [comment]
@CryptoGraphi yeah more contributions from others are also welcomed :)
