### ISSUE TITLE
More algos required

### ISSUE THREAD

**Issue by Abhiramborige** [Abhiramborige/Crypto-systems#4]
Any algorithms related to cryptography can be added along with updating Readme.md

**Comment by anubhav100rao** [comment]
I want to work on this issue.

**Comment by SUSHEELBAHUROJU** [comment]
Ok

**Comment by Abhiramborige** [comment]
@llSUSHEELII 
@anubhav100rao 
You both can work on... I will assign both.

**Comment by Abhiramborige** [comment]
please work on the algorithms other than one present in the repo.

**Comment by Abhiramborige** [comment]
i cant make the PRs from you as hactoberfest labelled because it would be a violation to the event.
